ARG IMAGE
FROM debian:$IMAGE
USER root
COPY wsl.conf /etc/wsl.conf
COPY init.sh init.sh
RUN chmod +x init.sh
COPY install-packages.sh install-packages.sh
RUN chmod +x install-packages.sh
RUN ./install-packages.sh
RUN ./init.sh
RUN echo 'root:root' | chpasswd
CMD ["bash"] .