ARG IMAGE
ARG DISTRIB
FROM $DISTRIB:$IMAGE
COPY wsl.conf /etc/wsl.conf
COPY init.sh init.sh
COPY install-packages.sh install-packages.sh
RUN chmod +x install-packages.sh && chmod +x init.sh && sh -c ./install-packages.sh && sh -c ./init.sh
CMD ["bash"] .
