# syntax = edrevo/dockerfile-plus

ARG IMAGE
FROM debian:$IMAGE

INCLUDE+ Dockerfile.base

# SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -fsSL https://get.docker.com -o get-docker.sh && \
    sudo sh ./get-docker.sh && \
    usermod -aG docker root && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    || true
    
CMD ["bash"] .