FROM debian:stable
COPY wsl.conf /etc/wsl.conf
RUN apt-get update && apt-get install -qq -y --no-install-recommends \
    nmon \
    nano \
    net-tools \
 && rm -rf /var/lib/apt/lists/*
CMD ["bash"]