# syntax = edrevo/dockerfile-plus

ARG IMAGE
FROM debian:$IMAGE

INCLUDE+ Dockerfile.base

RUN apt-get update && apt-get install -qq -y --no-install-recommends apt-utils
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN chmod +x get-docker.sh
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN sh ./get-docker.sh
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["bash"] .