name: Create
on: [workflow_dispatch]
# push:
#     branches: [ main ]
#     paths-ignore:
#       - '*.md'
#       - '.github/workflows/**'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile.multi.debian
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/debian:12, ${{ secrets.DOCKERHUB_USERNAME }}/debian:bookworm
            build-args: IMAGE=bookworm

# docker build -f Dockerfile.multi --build-arg "IMAGE=bookworm" -t test .

# docker build -f Dockerfile.multi --build-arg "IMAGE=trixie" -t test .

# docker build -f Dockerfile.multi --build-arg "IMAGE=stable" -t test .

# docker build -f Dockerfile.multi --build-arg "IMAGE=bullseye" -t test .




# docker build -f Dockerfile.multi.debian --build-arg "IMAGE=bookworm" -t runalsh/testdebian:bookworm -t runalsh/testdebian:12 .
# docker push runalsh/testdebian --all-tags


