name: DEBIAN STABLE+LATEST SLIM
on: [workflow_dispatch]
# push:
#     branches: [ main ]
#     paths-ignore:
#       - '*.md'
#       - '.github/workflows/**'

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          buildfor: ['stable-slim']
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile.multi.debian
            push: true
            # tags: ${{ secrets.DOCKERHUB_USERNAME }}/debian:12, ${{ secrets.DOCKERHUB_USERNAME }}/debian:bookworm
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/debian:${{ matrix.buildfor }}, ${{ secrets.DOCKERHUB_USERNAME }}/debian:latest-slim
            build-args: IMAGE=${{ matrix.buildfor }}



