name: DEBIAN STABLE+LATEST
on: # [workflow_dispatch]
  workflow_dispatch:
  push:
    branches: [ test ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
  # schedule:
  #   - cron:  '0 0 1 * *'

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          buildfor: ['stable']
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile.multi.debian
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/debian:test
            build-args: IMAGE=${{ matrix.buildfor }}



